# Generated by Django 4.1.2 on 2022-11-04 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0003_operation_slackusername_alter_operation_x_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='slackUsername',
        ),
    ]
